configGeneral:
  docker_image: registry.opensource.zalan.do/acid/spilo-15:3.0-p1
  enable_crd_validation: true
  enable_lazy_spilo_upgrade: true
  enable_pgversion_env_var: true
  enable_spilo_wal_path_compat: true
  enable_team_id_clustername_prefix: false
  etcd_host: ""
  kubernetes_use_configmaps: true
  max_instances: -1
  min_instances: -1
  resync_period: 30m
  repair_period: 5m

configAwsOrGcp:
  aws_region: eu-central-1
  kube_iam_role: ""
  log_s3_bucket: ""
  wal_s3_bucket: ""

configDebug:
  debug_logging: true
  enable_database_access: true

configKubernetes:
  cluster_domain: cluster.local
  cluster_labels: 
    application: spilo
  cluster_name_label: cluster-name
  custom_pod_annotations: {}
  downscaler_annotations: []
  enable_init_containers: true
  enable_pod_antiaffinity: true
  enable_pod_disruption_budget: true
  enable_readiness_probe: true
  enable_sidecars: true
  infrastructure_roles_secret_name: ""
  inherited_labels: []
  node_readiness_label: {}
  oauth_token_secret_name: ""
  pdb_name_format: "postgres-{cluster}-pdb"
  pod_antiaffinity_topology_key: "kubernetes.io/hostname"
  pod_deletion_wait_timeout: 10m
  pod_environment_configmap: ""
  pod_environment_secret: ""
  pod_management_policy: "ordered_ready"
  pod_priority_class_name: ""
  pod_role_label: spilo-role
  pod_service_account_definition: ""
  pod_service_account_name: postgres-pod
  pod_service_account_role_binding_definition: ""
  pod_terminate_grace_period: 5m
  secret_name_template: "{username}.{cluster}.credentials"
  spilo_fsgroup: 103
  spilo_privileged: false
  storage_resize_mode: pvc
  watched_namespace: "*"

configLoadBalancer:
  db_hosted_zone: db.example.com
  enable_master_load_balancer: false
  enable_replica_load_balancer: false
  master_dns_name_format: "{cluster}.{team}.{hostedzone}"
  replica_dns_name_format: "{cluster}-repl.{team}.{hostedzone}"

configLogging:
  enable_postgres_team_crd: false
  enable_postgres_team_crd_superusers: false
  log_level: INFO
  log_statements: ""

configTimeouts:
  pod_label_wait_timeout: 10m
  pod_deletion_wait_timeout: 10m
  ready_wait_interval: 4s
  ready_wait_timeout: 30s
  resource_check_interval: 3s
  resource_check_timeout: 10m

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi
