# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-app
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: httpd:2.4
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080        # External port
    targetPort: 80    # Container port
    protocol: TCP
  selector:
    app: apache
