apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
spec:
  replicas: 1  # Consider scaling based on application needs
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest  # Or a specific version (e.g., postgres:14-alpine)
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config  # Optional, if using a ConfigMap
