kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30300
    hostPort: 30300
    protocol: TCP  # For Grafana
  - containerPort: 30900
    hostPort: 30900
    protocol: TCP  # For Prometheus
  - containerPort: 30903
    hostPort: 30903
    protocol: TCP  # For Alertmanager
