apiVersion: v1
kind: Service
metadata:
  name: example-nodeport-service
spec:
  type: NodePort
  selector:
    app: example-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # Optional: Kubernetes will allocate one if not specified
