# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  labels:
    app: game
    type: config
data:
  # Configuration values as a properties file
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
    player.initial-lives=3
    player.level=1

---
# Pod using the ConfigMap
apiVersion: v1
kind: Pod
metadata:
  name: game-pod
  labels:
    app: game
spec:
  containers:
    - name: game-container
      image: nginx
      command: ['sh', '-c', 'cat /etc/config/game.properties']
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: game-config
