apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command: ['sh', '-c', 'date; echo "Hello from the Kubernetes cluster"']
          restartPolicy: OnFailure
