apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  username.txt: YWRtaW4xMjM=      # admin123
  password.txt: c3VwZXJzZWNyZXQ0NTY=  # supersecret456

---
apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
    - name: secret-test
      image: nginx
      command: ['sh', '-c', 'echo "Username: $USER" "Password: $PASSWORD"']
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username.txt
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password.txt
