# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4 
networking:
  disableDefaultCNI: true  # Disable default CNI
  podSubnet: "192.168.0.0/16"  # Calico's default subnet
nodes:
  - role: control-plane
  - role: worker
  - role: worker

