apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
  - name: db
    image: postgres:15
    env:
    - name: POSTGRES_PASSWORD
      value: "mypassword"
    - name: POSTGRES_DB
      value: "mydb" 
    ports:
    - containerPort: 5432
    startupProbe:
      tcpSocket:
        port: 5432
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      exec:
        command:
        - pg_isready
        - -U
        - postgres
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - pg_isready
        - -U
        - postgres
      initialDelaySeconds: 5
      periodSeconds: 5
